import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { VitePWA } from 'vite-plugin-pwa'

// Static single-page app. `npm run build` writes to dist/, which is what Vercel serves.
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),

    // The whole app is cached on first visit, so tapping a tag works with no
    // signal at all — which is the normal state of a chicken coop, a basement
    // laundry room, or anywhere with thick walls. Without this, an NFC tap out
    // of range gets a Safari error page instead of the task list.
    VitePWA({
      registerType: 'autoUpdate',
      injectRegister: 'auto',
      includeAssets: [],
      workbox: {
        // Everything the app is made of — it's small enough to hold entirely.
        // `png` is in the list for the home-screen icons: they are the one
        // thing here that has to be raster (see scripts/make-icons.mjs), and an
        // icon that 404s offline is an icon the phone forgets.
        globPatterns: ['**/*.{js,css,html,svg,png,woff2}'],
        // index.html goes through the network first so a new deploy lands on
        // the next load, falling back to the cached copy when offline.
        navigateFallback: 'index.html',
        cleanupOutdatedCaches: true,
        clientsClaim: true,
        skipWaiting: true,
      },
      manifest: {
        name: 'Home Maintenance',
        short_name: 'Home',
        description: 'A shared checklist for the house, opened by NFC stickers on the wall.',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        orientation: 'portrait',
        background_color: '#f1f5f9',
        theme_color: '#0f172a',
        // `any` and `maskable` have to be separate entries. They were one
        // entry marked "any maskable", which tells Android it may crop the
        // icon — and the icon it was pointed at has rounded corners, so the
        // launcher cropped the corners off a shape that already had them.
        // Maskable art has to be full-bleed with the glyph in the middle 80%;
        // that is a different file, generated by scripts/make-icons.mjs.
        icons: [
          { src: 'icon.svg', sizes: 'any', type: 'image/svg+xml', purpose: 'any' },
          { src: 'icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          { src: 'icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
    }),
  ],
})
